name: 'runs-on/action'
description: 'RunsOn Action for magic caching, and more'
runs:
  using: 'node20'
  main: 'index.js'
  post: 'post.js'
  # required, otherwise it could snapshot directories even if previous steps failed or were interrupted, which could lead to corrupted snapshots
  post-if: "success()"

inputs:
  show_env:
    description: 'Show all environment variables'
    required: false
    default: 'false'
  show_costs:
    description: 'Control how execution costs are displayed: "inline" for log output, "summary" for GitHub job summary, any other value disables the feature'
    required: false
    default: 'inline'
  snapshot_dirs:
    description: 'Newline separated list of directories (absolute paths) to snapshot across job execution.'
    required: false
    default: ''
  snapshot_version:
    description: 'Version of the snapshot to use'
    required: false
    default: 'v1'
  github_mirrors:
    description: 'Newline separated list of github repositories to mirror and locally checkout into `./mirrors`. E.g. setting `https://github.com/owner/repo@ref` will clone the repo into `./mirrors/owner/repo` and checkout the `ref` branch'
    required: false
    default: ''
  github_token:
    description: 'GitHub token to use for mirroring. Only useful if github_mirrors is enabled.'
    required: false
    default: ''
