name: 'runs-on/action'
description: 'RunsOn Action for magic caching, and more'
runs:
  using: 'node20'
  main: 'index.js'
  post: 'post.js'

inputs:
  show_env:
    description: 'Show all environment variables'
    required: false
    default: 'false'
  show_costs:
    description: 'Control how execution costs are displayed: "inline" for log output, "summary" for GitHub job summary, any other value disables the feature'
    required: false
    default: 'inline'
  snapshot_dirs:
    description: 'Newline separated list of directories to snapshot across job execution'
    required: false
    default: ''
  snapshot_version:
    description: 'Version of the snapshot to use'
    required: false
    default: 'v1'
  git_mirrors:
    description: 'Newline separated list of github repositories to mirror'
    required: false
    default: ''
