name: 'runs-on/action'
description: 'RunsOn Action for magic caching, and more'
runs:
  using: 'node20'
  main: 'index.js'
  post: 'post.js'

inputs:
  show-env:
    description: 'Show all environment variables'
    required: false
    default: 'false'
  display-costs:
    description: 'Control how execution costs are displayed: "inline" for console output, "summary" for GitHub job summary, any other value disables the feature'
    required: false
    default: 'inline'
