name: Test / Container

on:
  push:
    branches:
      - main
      - v*
      - feature/*
      - fix/*
  workflow_dispatch:

jobs:
  github:
    name: GitHub
    strategy:
      fail-fast: false
      matrix:
        container:
          - ubuntu:24.04
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./
        with:
          show_env: 'true'
          metrics: 'cpu,memory'
      - run: sleep 30

  runs-on:
    name: RunsOn
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu24-full-x64, ubuntu24-full-arm64]
        container:
          - ubuntu:24.04
    runs-on: runs-on=${{ github.run_id }}/cpu=2/family=m7/image=${{ matrix.image }}
    container: ${{ matrix.container }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./
        with:
          show_env: 'true'
          metrics: 'cpu,memory,network,disk'