name: Test / Default
on:
  push:
    branches:
      - main
      - v*
      - feature/*
  workflow_dispatch:

jobs:
  github:
    name: GitHub runners
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # expectation: this is just a noop on managed runners
      - uses: ./
      - run: sleep 30

  runs-on:
    name: RunsOn runners
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu24-full-x64, ubuntu24-full-arm64, windows22-base-x64]
    runs-on: runs-on=${{ github.run_id }}/cpu=2/family=m7/image=${{ matrix.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./
      - run: sleep 30